/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "AUTH_GOOGLE_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AUTH_GOOGLE_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AUTH_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AUTH_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "Assets": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "AuthCredentials": {
      "accessKeyId": string
      "region": string
      "secretAccessKey": string
      "type": "sst.sst.Linkable"
    }
    "AuthTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "ContentCompass": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "DOMAIN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DocsPage": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "LandingPage": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "MainApp": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "POSTHOG_HOST": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "POSTHOG_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PrimaryTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "PublicAssets": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "REGION": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STRIPE_COUPON_100_OFF": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STRIPE_COUPON_10_OFF": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STRIPE_CUSTOMER_PORTAL_LINK": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STRIPE_PRICE_BASIC": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STRIPE_PRICE_PREMIUM": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STRIPE_PUBLISHABLE_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STRIPE_SECRET_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STRIPE_WEBHOOK_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Stage": {
      "stage": string
      "type": "sst.sst.Linkable"
    }
    "TRANSACTIONAL_MAIL_LOCAL_PART": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TransactionalEmailIdentity": {
      "sender": string
      "type": "sst.aws.Email"
    }
  }
}
